
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nypvhpzfttvaghuuibhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55cHZocHpmdHR2YWdodXVpYmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzAzMjQsImV4cCI6MjA1OTM0NjMyNH0.y7R0gO4J5A5zOiEF5ZitHivv6W_8DQ2JxO78Kmu3h78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
